name: Build macOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install pyqt5 pyinstaller
    
    - name: Build macOS app
      run: |
        pyinstaller --onefile --windowed --name="PwdGenerator" PwdGenGui.py
    
    - name: Upload app
      uses: actions/upload-artifact@v4
      with:
        name: PwdGenerator-macOS
        path: dist/PwdGenerator.app
