name: Build Apps (Windows, macOS, Linux)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install pyqt5 pyinstaller
    
    - name: Build Windows exe
      run: |
        pyinstaller --onefile --windowed --name="PwdGenerator" PwdGenGui.py
    
    - name: Upload Windows exe
      uses: actions/upload-artifact@v4
      with:
        name: PwdGenerator-Windows
        path: dist/PwdGenerator.exe

  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install pyqt5 pyinstaller
    
    - name: Build macOS app
      run: |
        pyinstaller --onefile --windowed --name="PwdGenerator" PwdGenGui.py
    
    - name: Upload macOS app
      uses: actions/upload-artifact@v4
      with:
        name: PwdGenerator-macOS
        path: dist/PwdGenerator.app

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libxkbcommon-x11-0 libdbus-1-3
    
    - name: Install Python dependencies
      run: |
        pip install pyqt5 pyinstaller
    
    - name: Build Linux app
      run: |
        pyinstaller --onefile --windowed --name="PwdGenerator" PwdGenGui.py
    
    - name: Upload Linux app
      uses: actions/upload-artifact@v4
      with:
        name: PwdGenerator-Linux
        path: dist/PwdGenerator
